In [1]:
import numpy as np
import pandas as pd

## introduction

### Say "Hello, World!" With Python

In [197]:
print("Hello, World!")

Hello, World!


### Python If-Else

In [204]:
N = int(input())

if (N < 1) or (N > 100):
    print('out of the range')
elif (N % 2) == 0:
    if N < 6:
        print('Not Weird')
    elif N < 21:
        print('Weird')
    else:
        print('Not Weird')
else:
    print('Weird')

26
Not Weird


In [203]:
n = 26
if n%2==1:
    print("Weird")
elif n>=2 and n<=5:
    print("Not Weird")
elif n>=6 and n<=20:
    print("Weird")
else:
    print("Not Weird")

Not Weird


### Arithmetic Operators

In [205]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())

print(a + b)
print(a - b)
print(a * b)


5
6
11
-1
30


### Python: Division

In [206]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())

print(a // b)
print(a / b)

7
2
3
3.5


### Loops

In [207]:
if __name__ == '__main__':
    n = int(input())

for i in range(n):
    print(i ** 2)

7
0
1
4
9
16
25
36


### Write a function

In [208]:
def is_leap(year):

    leap = False
    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                leap = True
            else:
                leap = False
        else:
            leap = True
    
    return leap


year = int(input())
print(is_leap(year))

2100
False


### Print Function

In [209]:
if __name__ == '__main__':
    n = int(input())

import math

s = 0
for i in range(n + 1)[1:(n+1)]:
    s = s * (10 ** (int(math.log(i, 10)) + 1)) + i

print(s)

17
1234567891011121314151617


In [211]:
print(*range(1, int(input()) + 1), sep='')
for i in range(1,int(input()) + 1):
    print (i,end='')
    
list(map(lambda x: print(x,end=''),list(range(1,1+int(input())))))

12
123456789101112
13
12345678910111213

## Basic Data Types

### List Comprehensions

In [220]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())

ar = []
p = 0
for i in range(x + 1):
    for j in range(y + 1):
        for k in range(z + 1):
            if (i + j + k) != n:
                ar.append([])
                ar[p] = [i, j, k]
                p += 1

print(ar)


# mtd1
# [[i, j, k ] for i in range(x) for j in range(y) for k in range(z) if (i + j + k) != n]

3
3
5
4
[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 0, 3], [0, 0, 5], [0, 1, 0], [0, 1, 1], [0, 1, 2], [0, 1, 4], [0, 1, 5], [0, 2, 0], [0, 2, 1], [0, 2, 3], [0, 2, 4], [0, 2, 5], [0, 3, 0], [0, 3, 2], [0, 3, 3], [0, 3, 4], [0, 3, 5], [1, 0, 0], [1, 0, 1], [1, 0, 2], [1, 0, 4], [1, 0, 5], [1, 1, 0], [1, 1, 1], [1, 1, 3], [1, 1, 4], [1, 1, 5], [1, 2, 0], [1, 2, 2], [1, 2, 3], [1, 2, 4], [1, 2, 5], [1, 3, 1], [1, 3, 2], [1, 3, 3], [1, 3, 4], [1, 3, 5], [2, 0, 0], [2, 0, 1], [2, 0, 3], [2, 0, 4], [2, 0, 5], [2, 1, 0], [2, 1, 2], [2, 1, 3], [2, 1, 4], [2, 1, 5], [2, 2, 1], [2, 2, 2], [2, 2, 3], [2, 2, 4], [2, 2, 5], [2, 3, 0], [2, 3, 1], [2, 3, 2], [2, 3, 3], [2, 3, 4], [2, 3, 5], [3, 0, 0], [3, 0, 2], [3, 0, 3], [3, 0, 4], [3, 0, 5], [3, 1, 1], [3, 1, 2], [3, 1, 3], [3, 1, 4], [3, 1, 5], [3, 2, 0], [3, 2, 1], [3, 2, 2], [3, 2, 3], [3, 2, 4], [3, 2, 5], [3, 3, 0], [3, 3, 1], [3, 3, 2], [3, 3, 3], [3, 3, 4], [3, 3, 5]]


### Find the Runner-Up Score!

In [216]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())

list_arr = list(arr)
s = []
for i in list_arr:
    if i not in s:
        s.append(i)

# mtd1
# s=list(set(list_arr))

# mtd2
# big, sbig = -10000, -10000
# for i in list_arr:
#     if (i > big):
#         big, sbig = i, big
#     elif (i < big and i > sbig):
#         sbig = i
# sbig

s.sort()

print(s[-2])

5
5 6 6 4 8
6


### Nested Lists

In [ ]:
if __name__ == '__main__':
    l_name = []
    l_score = []
    n = int(input())
    for _ in range(n):
        name = input()
        l_name.append(name)
        score = float(input())
        l_score.append(score)


a_dict = dict(zip(l_name, l_score))

# snd_small
l_score.sort()

for i in range(1, n):
    if l_score[i] > l_score[i - 1]:
        snd_small = l_score[i]
        break

result = []
for key,value in a_dict.items():
    if value==snd_small:
        result.append(key)
        
# 按名字首字母排序
result.sort()

for i in result:
    print(i)
    
    
# # mtd1
# from collections import defaultdict
# marks = defaultdict(list)
# for _ in range(int(input())):
#     name, mark = input(), float(input())
#     marks[mark].append(name)

# print("\n".join(map(str, sorted(marks[sorted(marks.keys())[1]]))))



# # mtd2
# def secondLowestMarks(students):
#     lowest_mark = min(students, key = lambda stu: stu[1])[1];
#     students = [stu for stu in students if stu[1] != lowest_mark]
#     #filter(lambda stu: stu[1] == lowest_mark, students);
#     second_lowest_mark = min(students, key = lambda stu: stu[1])[1];
#     return sorted([stu[0] for stu in students if stu[1] == second_lowest_mark]);

# def secondLowestMarks2(students):
#     "If there's a tie for lowest mark we include all."
#     students.sort();
#     picked_students = sorted(filter(lambda x: x[1] == students[1][1], students));
#     return [stu[0] for stu in picked_students];

# if __name__ == "__main__":
#     num_students = int(input());
#     students = [[input(),float(input())] for i in range(num_students)];
#     for student in secondLowestMarks(students):
#         print(student);

### Finding the percentage

In [ ]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    
student_marks_avg = {}
for key in student_marks.keys():
    student_marks_avg[key] = sum(student_marks[key]) / len(student_marks[key])
    
query_name = input()

print('%.2f' % student_marks_avg[query_name])

# # mtd1
# data = {}
# for _ in range(int(input())):
#     name, *marks = input().split()
#     data[name] = [float(m) for m in marks]
# marks = data[input()]
# print("%.2f" % (sum(marks)/len(marks)))

### Lists

In [ ]:
if __name__ == '__main__':
    N = int(input())
    
    command_list = []
    for _ in range(N):
        command_name, *line = input().split()
        command = list(map(int, line))
        command.insert(0, command_name)
        command_list.append(command)

    
target_list = []
for command in command_list:
    if command[0] == 'insert':
        target_list.insert(command[1], command[2])
    elif command[0] == 'print':
        print(target_list)
    elif command[0] == 'remove':
        target_list.remove(command[1])
    elif command[0] == 'append':
        target_list.append(command[1])
    elif command[0] == 'sort':
        target_list.sort()
    elif command[0] == 'pop':
        target_list.pop()
    else:
        target_list.reverse()
        

# # mtd1
# test =int(input())
# s=[]
# for _ in range (test):
#     cmd=list(input().split())
    
#     if cmd[0]=='insert':
#         s.insert(int(cmd[1]),int(cmd[2]))
#     elif cmd[0]=="remove":
#         s.remove(int(cmd[1]))
#     elif cmd[0]=="append":
#         s.append(int(cmd[1]))
#     elif cmd[0]=="sort":
#         s.sort()
#     elif cmd[0]=="pop":
#         s.pop()
#     elif cmd[0]=="reverse":
#         s.reverse()
#     elif cmd[0]=="count":
#         v=s.count(int(cmd[1]))
#         print(v)
#     elif cmd[0]=="index":
#         x=s.index(int(cmd[1]))
#         print(x)
#     elif cmd[0]== 'print':
#         print(s)

### Tuples

In [ ]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())

integer_tuple = tuple(integer_list)

# mtd1
# integer_tuple = tuple([int(n) for n in input().split()])
print(hash(integer_tuple))

## Strings

### sWAP cASE

In [ ]:
def swap_case(s):
    new_s = ''
    for i in s:
        if i.isalpha():
            if i.isupper():
                new_s = new_s + i.lower()
            else:
                new_s = new_s + i.upper()
        else:
            new_s = new_s + i
    return new_s

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)
    

# # mtd1
# string_input = input()
# print(string_input.swapcase())


# # mtd2
# import sys

# for line in sys.stdin:
#     s.join(strings)以s连接strings 
#     line = ''.join([c.upper() if c.islower() else c.lower() for c in line])
#     print(line)

### String Split and Join

In [ ]:
def split_and_join(line):
    # write your code here
    strList = line.split(" ")
    return "-".join(strList)

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

### What's Your Name?

In [ ]:
def print_full_name(a, b):
    print("Hello %s %s! You just delved into python." % (a, b))
    
## mtd1
#     print("Hello {} {}! You just delved into python.".format(a, b))

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

### Mutations

In [328]:
def mutate_string(string, position, character):
    
    # 1st
    l = list(string)
    l[position] = character
    new_string = ''.join(l)

    # # 2nd
    # new_string = string[:(position - 1)] + character + string[(position + 1):]
    return new_string


if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

abcdzfg
4 e
abcdefg


### Find a string

In [330]:
def count_substring(string, sub_string):
    
    num = 0
    len_sub = len(sub_string)
    for i in range(len(string)): # for i in range(len(string) - len_sub + 1)
        if len(string) < len_sub:
            break
        elif string[i:(i + len_sub)] == sub_string:
            num += 1

    return num


# # mtd1
# for i in range(0, len(S)):
#     # S.count(sub[, start[, end]])
#     count += S.count(ss,i,i+len(ss)) 
# print(count)


if __name__ == '__main__':
    
    # str.strip() 移除字符串头尾指定的字符（默认为空格或换行符）或字符序列
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

abcabdefabc
abc
2


### String Validators

In [333]:
if __name__ == '__main__':
    s = input().strip()

    len_s = len(s)
    
    #  if the string has a alphanumeric (a-z, A-Z and 0-9)
    i = 0
    while i < len(s):
        if s[i].isalnum():
            print('True')
            break
        else:
            i += 1
    if i == len(s):
        print('False')

    #  if the string has a alphabeta(a-z, A-Z)
    while i < len(s):
        if s[i].isalpha():
            print('True')
            break
        else:
            i += 1
    if i == len(s):
        print('False')

    #  if the string has a digit(0-9)
    i = 0
    while i < len(s):
        if s[i].isdigit():
            print('True')
            break
        else:
            i += 1
    if i == len(s):
        print('False')

    #  if the string has a lowercase(a-z)
    i = 0
    while i < len(s):
        if s[i].islower():
            print('True')
            break
        else:
            i += 1
    if i == len(s):
        print('False')
    
    #  if the string has a uppercase(A-Z)
    i = 0
    while i < len(s):
        if s[i].isupper():
            print('True')
            break
        else:
            i += 1
    if i == len(s):
        print('False')
        
        
# # mtd1
# inp = input()
# print(any(x.isalnum() for x in inp))
# print(any(x.isalpha() for x in inp))
# print(any(x.isdigit() for x in inp))
# print(any(x.islower() for x in inp))
# print(any(x.isupper() for x in inp))


# # mtd2
# s =input()
# one=False
# two=False
# three=False
# four=False
# five=False

# for c in s:
#     if not one:
#         one=c.isalnum()
#     if not two:
#         two=c.isalpha()
#     if not three:
#         three=c.isdigit()
#     if not four:
#         four=c.islower()
#     if not five:
#         five=c.isupper()

# print(one)
# print(two)
# print(three)
# print(four)
# print(five)

qA2
True
True
True
True
True


### Text Alignment

In [98]:
#Replace all ______ with rjust, ljust or center. 

thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c * (2 * i + 1)).center(thickness * 2 - 1, ' '))

#Top Pillars   
for i in range(thickness+1):
    print((c*thickness).center(thickness*2, ' ') + (c*thickness).center(thickness*6, ' '))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6, ' '))       

for i in range(thickness+1):
    print((c*thickness).center(thickness*2, ' ') + (c*thickness).center(thickness*6, ' '))  

#Bottom Cone
for i in range(thickness):
    print((c * (2 * (thickness - i) - 1)).center(thickness * 2, ' ').rjust(thickness * 6, ' '))


7
      H      
     HHH     
    HHHHH    
   HHHHHHH   
  HHHHHHHHH  
 HHHHHHHHHHH 
HHHHHHHHHHHHH
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH    
   HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH    
   HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH    
   HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH    
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH      

### Text Wrap

In [ ]:
import textwrap
# import math

def wrap(string, max_width):

    # num = math.ceil(len(string) / max_width) - 1
    # target = []
    # for i in range(num):
    #     target.append(string[i * max_width : (i + 1) * max_width])

    # target.append(string[(i + 1) * max_width:])
    
    # for i in target:
    #     print(i)
    
    return textwrap.fill(string, max_width)


if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)


### Designer Door Mat

In [105]:
N, M = input().split() #N must be an odd number, M = 3 * N

N = int(N)
M = int(M)
c = '.|.'

num = N // 2
for i in range(num): # for i in range(1,N,2):
    print((c * (i * 2 + 1)).center(M, '-'))

print('WELCOME'.center(M, '-'))

for i in range(num):
    print((c * ((num - i) * 2 - 1)).center(M, '-'))

9 27
------------.|.------------
---------.|..|..|.---------
------.|..|..|..|..|.------
---.|..|..|..|..|..|..|.---
----------WELCOME----------
---.|..|..|..|..|..|..|.---
------.|..|..|..|..|.------
---------.|..|..|.---------
------------.|.------------


### Alphabet Rangoli

In [156]:
def print_rangoli(size):
    
    c_line  = 'a'
    for i in range(size - 1):
        c_line = chr(i + 98) + '-' + c_line + '-' + chr(i + 98)

    tt_line = c_line + '\n'
    for i in range(size - 1):
        c_line = (c_line[:(size * 2 - 2)] + c_line[(size * 2 + 2):]).center(size * 4 - 3, '-')
        tt_line = c_line + '\n' + tt_line + c_line + '\n'
    
    return print(tt_line)
    
    
if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

7
------------g------------
----------g-f-g----------
--------g-f-e-f-g--------
------g-f-e-d-e-f-g------
----g-f-e-d-c-d-e-f-g----
--g-f-e-d-c-b-c-d-e-f-g--
g-f-e-d-c-b-a-b-c-d-e-f-g
--g-f-e-d-c-b-c-d-e-f-g--
----g-f-e-d-c-d-e-f-g----
------g-f-e-d-e-f-g------
--------g-f-e-f-g--------
----------g-f-g----------
------------g------------



In [342]:
#mtd1
import string


n = int(input())

mid = n-1
for row in range(n*2-1):
    line = ""
    for col in range(n*2-1):
        d = abs(row-mid) + abs(col-mid)
#         print('%d %d %d' % (row, col, d))
        if (col>0): 
            line += "-"
        if d>=n: 
            line += "-"
        else: 
            line += string.ascii_lowercase[d]
    print(line)
    

5
--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


### Capitalize

In [343]:
def solve(s):
    
    s = s.lower()
    new_s = s[0].upper()
        
    for i in range(1, len(s)):
        if s[i - 1] == ' ':
            new_s = new_s + s[i].upper()
        else:
            new_s = new_s + s[i]
            
    return new_s

# list1=s.split(' ')
# for i in list1:
#     print(i.capitalize(),end=' ')
# # s.capitalize() Return a capitalized version of S, i.e. make the first character have upper case and the rest lower case.

solve('rYan oLigen xu tenG')

'Ryan Oligen Xu Teng'

In [344]:
list1='rYan oLigen xu tenG'.split(' ')
list1
for i in list1:
    print(i.capitalize(),end=' ')


['rYan', 'oLigen', 'xu', 'tenG']

Ryan Oligen Xu Teng 

### The Minion Game

In [174]:
def minion_game(string):
    s = string.upper()
    k_score = 0
    s_score = 0

    len_s = len(s)
    for i in range(len_s):
        if s[i] in 'AEIOU':
            k_score = k_score + len_s - i
        else:
            s_score = s_score + len_s - i

    if k_score > s_score:
        return print('Kevin %d' % k_score)
    elif k_score == s_score:
        return print('Draw')
    else:
        return print('Stuart %d' % s_score) # return print('Stuart', s_score)

if __name__ == '__main__':
    s = input()
    minion_game(s)

alsneiwajskwof
Stuart 63


### Merge the Tools!

In [196]:
def merge_the_tools(string, k):
    
    substr_num = int(len(string) / k)
    string_fin = ''
    
#     for i in range(0, len(string), k):
#         substr_org = string[i: (i + k)]
    
    for i in range(substr_num):
        substr_org = string[i * k:(i + 1) * k]
        substr_fin = ''
        for i in substr_org:
            if i not in substr_fin:
                substr_fin = substr_fin + i
        string_fin = string_fin + substr_fin + '\n'

    return print(string_fin)


if __name__ == '__main__':
    string, k = input(), int(input())
    merge_the_tools(string, k)
    
    
    
# # mtd1
# a = input()
# K = int(input())
# for n in range(len(a)//K):
#     s = set([])
#     out = ""
#     for i in range(K*n, K*(n+1)):
#         if a[i] not in s:
#             s.add(a[i])
#             out += a[i]
#     print(out)

AABCAAADA
3
AB
CA
AD



## Itertools

### itertools.product()

In [249]:
from itertools import product

# cartesian product 笛卡尔积
# print list(product([1,2,3],repeat = 2))
# print list(product([1,2,3],[3,4]))

# A = [[1,2,3],[3,4,5]]
# print list(product(*A))

# B = [[1,2,3],[3,4,5],[7,8]]
# print list(product(*B))


a = list(map(int, input().split()))
b = list(map(int, input().split()))
prod_ab = list(product(a, b))

for i in prod_ab[:-1]:
    print(i, end = ' ')
print(prod_ab[-1])

# for i in l:
#     print(i,end = ' ')

# print(*list(product(a, b)))
# print(' '.join([str(i) for i in list(product(a,b))]))

1 2 3
3 2 1
(1, 3) (1, 2) (1, 1) (2, 3) (2, 2) (2, 1) (3, 3) (3, 2) (3, 1)


### itertools.permutations()

In [ ]:
from itertools import permutations

# >>> print permutations(['1','2','3'])
# <itertools.permutations object at 0x02A45210>
# >>> 
# >>> print list(permutations(['1','2','3']))
# [('1', '2', '3'), ('1', '3', '2'), ('2', '1', '3'), ('2', '3', '1'), ('3', '1', '2'), ('3', '2', '1')]
# >>> 
# >>> print list(permutations(['1','2','3'],2))
# [('1', '2'), ('1', '3'), ('2', '1'), ('2', '3'), ('3', '1'), ('3', '2')]
# >>>
# >>> print list(permutations('abc',3))
# [('a', 'b', 'c'), ('a', 'c', 'b'), ('b', 'a', 'c'), ('b', 'c', 'a'), ('c', 'a', 'b'), ('c', 'b', 'a')]


stringA, k = input().split()
k = int(k)

pm_list = list(permutations(stringA, k))
pm_list.sort()

for item in pm_list:
    s = ''
    for j in range(k):
        s = s + item[j]
    print(s)


    
# for item in pm_list:
#     print(''.join(item))


## Math

### Polar Coordinates

In [2]:
import cmath

c = complex(input())

print(abs(c))
print(cmath.phase(c))




# # mtd2
# print(*cmath.polar(complex(input())), sep='\n')

# # mtd1
# import cmath

# N = input()

# if N[0] == '-':
#     if '-' in N[1:]:
#         N = N.split('-')
#         Re = -float(N[1])
#         Im = -float(N[2][:-1])
#     else:
#         N = N.split('+')
#         Re = float(N[0])
#         Im = float(N[1][:-1])
# else:
#     if '-' in N:
#         N = N.split('-')
#         Re = float(N[0])
#         Im = -float(N[1][:-1])
#     else:
#         N = N.split('+')
#         Re = float(N[0])
#         Im = float(N[1][:-1])

# C = complex(Re, Im)
# print(abs(C))
# print(cmath.phase(C))

3-4j
5.0
-0.9272952180016122


### Find Angle MBC

In [15]:
import math

c = int(input())
a = int(input())

alpha = math.atan(c / a) / 2 / math.pi * 360
# math.degrees(math.atan(c / a))

print(str(round(alpha)) + '°')

10
12
40°


### Mod Divmod

In [39]:
a = int(input())
b = int(input())

print(a // b) # quotient
print(a % b) # modulo
print(divmod(a, b)) 

177
10
17
7
(17, 7)


### Power - Mod Power

In [41]:
a = int(input())
b = int(input())
m = int(input())
print(pow(a, b)) # a ** b
print(pow(a, b, m)) # a** b % m

3
4
5
81
1


### Integers Come In All Sizes

In [42]:
a = int(input())
b = int(input())
c = int(input())
d = int(input())
print(pow(a, b) + pow(c, d)) # a ** b + c ** d

9
29
7
27
4710194409608608369201743232


### Triangle Quest

In [43]:
for i in range(1,int(input())):
    print(10 ** i // 9 * i)

5
1
22
333
4444


### Triangle Quest 2

In [26]:
for i in range(1,int(input())+1): #More than 2 lines will result in 0 score. Do not leave a blank line also
    print("".join(map(str, (list(range(1, i)) + list(range(i, 0, -1))))))
    
# for i in range(1,int(input())+1):
#      print((10**i//9)**2)

# for i in range(1,int(raw_input())+1): #More than 2 lines will result in 0 score. Do not leave a blank line also
#     print  reduce(lambda x, y: x + (10 ** (y - 1)), range(1, i + 1))**2

5
1
121
12321
1234321
123454321


## Sets

### introduction to Sets

In [ ]:
# >>> print set()
# set([])

# >>> print set('HackerRank')
# set(['a', 'c', 'e', 'H', 'k', 'n', 'r', 'R'])

# >>> print set([1,2,1,2,3,4,5,6,0,9,12,22,3])
# set([0, 1, 2, 3, 4, 5, 6, 9, 12, 22])

# >>> print set((1,2,3,4,5,5))
# set([1, 2, 3, 4, 5])

# >>> print set(set(['H','a','c','k','e','r','r','a','n','k']))
# set(['a', 'c', 'r', 'e', 'H', 'k', 'n'])

# >>> print set({'Hacker' : 'DOSHI', 'Rank' : 616 })
# set(['Hacker', 'Rank'])

# >>> print set(enumerate(['H','a','c','k','e','r','r','a','n','k']))

     
def average(array):
    return sum(set(array)) / len(set(array))

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

In [ ]:
myset = {1, 2} # Directly assigning values to a set
myset = set()  # Initializing a set
myset = set(['a', 'b']) # Creating a set from a list
myset

myset.add('c')
myset.add('a') # As 'a' already exists in the set, nothing happens
myset.add((5, 4))
myset

myset.update([1, 2, 3, 4]) # update() only works for iterable objects
myset.update({1, 7, 8})
myset.update({1, 6}, [5, 13])
myset

myset.discard(10)
myset
myset.remove(13)
myset

a = {2, 4, 5, 9}
b = {2, 4, 11, 12}
a.union(b) # Values which exist in a or b
a.intersection(b) # Values which exist in a and b
a.difference(b) # Values which exist in a but not in b

In [ ]:
n = int(input())
stampSet = set()
for i in range(n):
    stamp = input()
    stampSet.add(stamp)

print(len(stampSet))


In [ ]:
m = int(input())
a = set(list(map(int, input().split())))
n = int(input())
b = set(list(map(int, input().split())))
c = (a - b).union(b - a)
d = list(c)
d.sort()
for i in d:
    print(i)

## Date and Time

### Calendar Module

[calendar functions](https://docs.python.org/2/library/calendar.html#calendar.setfirstweekday)

In [9]:
import calendar

print(calendar.TextCalendar(firstweekday=6).formatyear(2019))

                                  2019

      January                   February                   March
Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa
       1  2  3  4  5                      1  2                      1  2
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       3  4  5  6  7  8  9
13 14 15 16 17 18 19      10 11 12 13 14 15 16      10 11 12 13 14 15 16
20 21 22 23 24 25 26      17 18 19 20 21 22 23      17 18 19 20 21 22 23
27 28 29 30 31            24 25 26 27 28            24 25 26 27 28 29 30
                                                    31

       April                      May                       June
Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa
    1  2  3  4  5  6                1  2  3  4                         1
 7  8  9 10 11 12 13       5  6  7  8  9 10 11       2  3  4  5  6  7  8
14 15 16 17 18 19 20      12 13 14 15 16 17 18       9 10 11 12 13 14 15
21 22 23 24 25 26 27      19 20 21 22 23 24 

In [13]:
import calendar

m, d, y = map(int, input().split())

wd = calendar.weekday(y, m, d)
if wd == 0:
    print('MONDAY')
elif wd == 1:
    print('TUESDAY')
elif wd == 2:
    print('WEDNESDAY')
elif wd == 3:
    print('THURSDAY')
elif wd == 4:
    print('FRIDAY')
elif wd == 5:
    print('SATURDAY')
else:
    print('SUNDAY') 

# days = {0:'MONDAY',1:'TUESDAY',2:'WEDNESDAY',3:'THURSDAY',4:'FRIDAY',5:'SATURDAY',6:'SUNDAY'}
# print(days[calendar.weekday(y,m,d)])    

# week   = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
# print(week[(calendar.weekday(y, m, d) % 7].upper())

# print(calendar.day_name[wd].upper())

2019 01 02
WEDNESDDAY


## Collections

### collections.Counter()

In [406]:
from collections import Counter


# >>> myList = [1,1,2,3,4,5,3,2,3,4,2,1,2,3]
# >>> print Counter(myList)
# Counter({2: 4, 3: 4, 1: 3, 4: 2, 5: 1})

# >>> print Counter(myList).items()
# [(1, 3), (2, 4), (3, 4), (4, 2), (5, 1)]
 
# >>> print Counter(myList).keys()
# [1, 2, 3, 4, 5]
 
# >>> print Counter(myList).values()
# [3, 4, 4, 2, 1]


# number of shoes
shoe_num = int(input())
# size of shoes
shoe_size = list(map(int, input().split()))
shoe_counter = Counter(shoe_size)
# number of customers
cm_num = int(input())
# customerg payment

earn = 0
for i in range(cm_num):
    payment = list(map(int, input().split()))
    if payment[0] in shoe_counter:
        if shoe_counter[payment[0]] > 0:
#     if payment[0] in shoe_counter and shoe_counter[payment[0]] > 0:
            earn += payment[1]
            shoe_counter[payment[0]] -= 1
# # mtd1
# for i in range(cm_num):
#     sz, py = map(int, input().split())
#     if shoe_counter[sz]:
#         shoe_counter[sz] -= 1
#         earn += py


# # mtd2
# for i in range(cm_num):
#     sz, py = map(int, input().split())
#     if sz in shoe_counter.elements(): # shoe_counter[sz]值减少到0，则elements不再出现
#         shoe_counter[sz] -= 1
#         earn += py

earn

10
2 3 4 5 6 8 7 6 5 18
6
6 55
6 45
6 55
4 40
18 60
10 50


200

### DefaultDict Tutorial

In [2]:
from collections import defaultdict
d = defaultdict(list)
d['python'].append("awesome")
d['something-else'].append("not relevant")
d['python'].append("language")
for i in d.items():
    print(i)

('python', ['awesome', 'language'])
('something-else', ['not relevant'])


In [270]:
# The first line contains integers,  and  separated by a space. 
# The next  lines contains the words belonging to group . 
# The next  lines contains the words belonging to group .

n, m = map(int, input().split())


groupA = []
for i in range(n):
    groupA.append(input())
    
groupB = []
for j in range(m):
    groupB.append(input())


ind = []

for str_i in groupB:
    ind_inner = []
    if str_i not in groupA:
        ind_inner.append(-1)
    else:
        for k in range(n):
            if str_i == groupA[k]:
                ind_inner.append(k + 1)
    ind.append(ind_inner)

for i in ind:
    for j in i[:-1]:
        print(j, end = ' ')
    print(i[-1])

5 2
a
a
b
a
b
a
b
1 2 4
3 5


In [65]:
from collections import defaultdict
n, m = input().split()
d = defaultdict(list)

for i in range(int(n)):
    d[input()].append(str(i+1))
    
for _ in range(int(m)):
    i = input()
    print(' '.join(d[i])) if d[i] else print(-1)

5 2
a
a
b
a
b
a
1 2 4
b
3 5


### collections.namedtuple()

In [66]:
from collections import namedtuple
Point = namedtuple('Point','x,y')
pt1 = Point(1,2)
pt2 = Point(3,4)
dot_product = ( pt1.x * pt2.x ) +( pt1.y * pt2.y )
print(dot_product)

Car = namedtuple('Car','Price Mileage Colour Class')
xyz = Car(Price = 100000, Mileage = 30, Colour = 'Cyan', Class = 'Y')
print(xyz)
Car(Price=100000, Mileage=30, Colour='Cyan', Class='Y')
print(xyz.Class)


#  calculate the average marks of the students
n = int(input())
Student = namedtuple('Student', input())
sum_mark = 0
for i in range(n):
    a = Student(*input().split())
    sum_mark += int(a.MARKS)
    
# sum(float(Student(*input().strip().split()).MARKS) for _ in range(n))/n

print('%.2f' % (sum_mark / n))

11
Car(Price=100000, Mileage=30, Colour='Cyan', Class='Y')


Car(Price=100000, Mileage=30, Colour='Cyan', Class='Y')

Y
5
ID MARKS NAME CLASS
1 97 raymond 7
2 50 steven 4
3 91 adrian 9
4 72 stewart 5
5 80 peter 6
78.00


### Collection.deque()

In [74]:
# >>> from collections import deque
# >>> d = deque()
# >>> d.append(1)
# >>> print d
# deque([1])
# >>> d.appendleft(2)
# >>> print d
# deque([2, 1])
# >>> d.clear()
# >>> print d
# deque([])
# >>> d.extend('1')
# >>> print d
# deque(['1'])
# >>> d.extendleft('234')
# >>> print d
# deque(['4', '3', '2', '1'])
# >>> d.count('1')
# 1
# >>> d.pop()
# '1'
# >>> print d
# deque(['4', '3', '2'])
# >>> d.popleft()
# '4'
# >>> print d
# deque(['3', '2'])
# >>> d.extend('7896')
# >>> print d
# deque(['3', '2', '7', '8', '9', '6'])
# >>> d.remove('2')
# >>> print d
# deque(['3', '7', '8', '9', '6'])
# >>> d.reverse()
# >>> print d
# deque(['6', '9', '8', '7', '3'])
# >>> d.rotate(3)
# >>> print d
# deque(['8', '7', '3', '6', '9'])


# Perform append, pop, popleft and appendleft methods on an empty deque
from collections import deque
d = deque()
n = int(input())
for i in range(n):
    a = input().split()
    if a[0] == 'append':
        d.append(a[1])
    elif a[0] == 'pop':
        d.pop()
    elif a[0] == 'popleft':
        d.popleft()
    elif a[0] == 'appendleft':
        d.appendleft(a[1])

print(' '.join(d))

6
append 1
append 2
append 3
appendleft 4
pop


'3'

popleft


'4'

deque(['1', '2'])


### Company Logo

In [151]:
# Print the three most common characters along with their occurrence count each on a separate line. 
# Sort output in descending order of occurrence count. 
# If the occurrence count is the same, sort the characters in alphabetical order.

s = input().strip()
from collections import Counter
s1 = Counter(s)

k = list(s1.keys())
v = list(s1.values())

import pandas as pd
df = pd.DataFrame({'k':k, 'v':v}, dtype = str)

df1 = df.sort_values(by = ['v', 'k'], ascending = (False, True))



for i in range(3):
    print(' '.join(df1.iloc[i]))

google
g 2
o 2
e 1


### Piling Up!

In [150]:
t = int(input())
for i in range(t):
    n = int(input())
    sideLen = list(map(int, input().split()))
    
    if sideLen[0] > sideLen[-1]:
        cube1 = sideLen[0]
        sideLen.pop(0)
    else:
        cube1 = sideLen[-1]
        sideLen.pop(-1)
    
    for i in range(n - 1):
        if sideLen[0] > sideLen[-1]:
            if sideLen[0] > cube1:
                print('No')
                break
            else:
                cube1 = sideLen[0]
                sideLen.pop(0)
        else:
            if sideLen[-1] > cube1:
                print('No')
                break
            else:
                cube1 = sideLen[-1]
                sideLen.pop(-1)
    if i == (n - 2):
        print('Yes')
    

2
6
4 3 2 1 3 4


4

4

3

3

2

1

Yes
3
1 3 2


2

No


### Word Order

In [138]:
# # Enter your code here. Read input from STDIN. Print output to STDOUT
# if __name__ == '__main__':
#     n = int(input())
#     words = []
#     for _ in range(n):
#         word = input()
#         words.append(word)

# # line1
# unique_word = []

# for word in words:
#     if word not in unique_word:
#         unique_word.append(word)

# print(len(unique_word))

# # line2
# count_words = []
# for word in unique_word:
#     count_words.append(words.count(word))
    
# for i in range(len(unique_word) - 1):
#     print(count_words[i], end=' ')
# print(count_words[-1])


# given n words. Some words may repeat. For each word, output its number of occurrences. The output order should correspond with the input order of appearance of the word
# from collections import Counter

n = int(input())
words = []
for i in range(n):
    words.append(input())

word_dict = Counter(words)

print(len(word_dict))
for i in word_dict.values():
    print(i, end = ' ')

# # mth1    
# from collections import OrderedDict
# d=OrderedDict()
# n=int(input())
# for i in range(n):
#     s=input()
#     if s in d.keys():
#         d[s]+=1
#     else:
#         d[s]=1
# print(len(d.keys()))
# print(' '.join([str(d[k]) for k in d.keys()]))


# # mth2
# count = int(input())
# order = []
# words = {}

# for i in range(0, count):
#     word = input()
    
#     if word in words:
#         words[word] += 1
#     else:
#         order.append(word)
#         words[word] = 1

# print(len(words))

# for word in order:
#     print(words[word], end=" ")

4
bcdef
abcdefg
bcde
bcdef
2 1 1 

## Errors and Exceptions

### Exceptions

[build-in exceptions](https://docs.python.org/2/library/exceptions.html#module-exceptions)

In [17]:
n = int(input())

for i in range(n):
    a, b = input().split()
    try:
        print(int(a) // int(b))
    except ZeroDivisionError as error:
        print("Error Code:", error)
    except ValueError as v:
        print('Error Code:', error)

3
3 0
Error Code: integer division or modulo by zero
3 *
Erroe Code: invalid literal for int() with base 10: '*'
3 9
0


## Regex and Parsing
### Detect Floating Point Number

In [3]:
import re 
re.search(r"ly", "similarly")
bool(re.match(r"ly", "similarly"))
bool(re.match(r"ly", "ly should be in the beginning"))

<_sre.SRE_Match object; span=(7, 9), match='ly'>

False

True

## Numpy

### Arrays

In [67]:
import numpy as np
a = np.array([1, 2, 3, 4, 5]) # numpy array is similar to list, but every element of an array must be the same type
a
b = np.array([1, 2, 3, 4, 5], float)
b
c = np.array([1, '2', 3])
c

array([1, 2, 3, 4, 5])

array([1., 2., 3., 4., 5.])

array(['1', '2', '3'], dtype='<U11')

In [56]:
# You are given a space separated list of numbers. 
# Your task is to print a reversed NumPy array with the element type float.

def arrays(arr):
    return np.array(arr[::-1], float)
    # complete this function
    # use numpy.array

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### Shape and Reshape

In [69]:
# You are given a space separated list of nine integers. Your task is to convert this list into a 3*3 NumPy array.

a = list(map(int, input().split()))

print(np.array(a).reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Transpose and Flatten

In [4]:
import numpy as np

n, m = map(int, input().split())

a = []
for i in range(n):
    a.append(list(map(int, input().split())))
    
# lista=[list(map(int,input().split())) for i in range(n)]
# a=numpy.array(lista)

arr = np.array(a)

print(np.transpose(arr))
print(arr.flatten())


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


### Concatenate

In [10]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_3 = np.array([7,8,9])
np.concatenate((array_1, array_2, array_3))

array_4 = np.array([[1,2,3],[0,0,0]])
array_5 = np.array([[0,0,0],[7,8,9]])
np.concatenate((array_4, array_5))
np.concatenate((array_4, array_5), axis = 1)


n, m, p = map(int, input().split())
list_np = [list(map(int, input().split())) for i in range(n)]
list_mp = [list(map(int, input().split())) for j in range(m)]
print(np.concatenate((np.array(list_np), np.array(list_mp))))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0],
       [7, 8, 9]])

array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 7, 8, 9]])

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### Zeros and Ones

In [31]:
np.zeros((1, 2))
np.zeros((1, 2), dtype = np.int)

np.ones((1, 2))
np.ones((1, 2), dtype = np.int)


*a, = map(int, input().split())
np.zeros(tuple(a), dtype = np.int)
np.ones(tuple(a), dtype = np.int)

array([[0., 0.]])

array([[0, 0]])

array([[1., 1.]])

array([[1, 1]])

3 3 3


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

### Eye and Identity

In [32]:
np.identity(3) #  3 is for  dimension 3 X 3
np.eye(8, 7, k = 1) # 8 X 7 Dimensional array with first upper diagonal 1
np.eye(8, 7, k = -2) # 8 X 7 Dimensional array with second lower diagonal 1


# an array of size n * m with its main diagonal elements as 1's and 0's everywhere else.
n, m = map(int, input().split())
np.eye(n, m)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])

3 3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
n, m = map(int, input().split())
np.set_printoptions(sign=' ')
print(np.eye(n, m))

5 5
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [34]:
n, m = map(int, input().split())
# np.set_printoptions(sign=' ')
print(np.eye(n, m))

5 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Array Mathematics

In [38]:
a = np.array([1,2,3,4], float)
b = np.array([5,6,7,8], float)

a + b          
np.add(a, b)

a - b               
np.subtract(a, b)

a * b               
np.multiply(a, b)

a / b            
np.divide(a, b)

a % b            
np.mod(a, b)  

a**b          
np.power(a, b)  


n, m = map(int, input().split())
a = np.array([list(map(int, input().split())) for i in range(n)])
b = np.array([list(map(int, input().split())) for i in range(n)])
print(a + b)
print(a - b)
print(np.multiply(a, b))
print(np.divide(a, b))
print(a % b)
print(np.power(a, b))


array([  6.,   8.,  10.,  12.])

array([  6.,   8.,  10.,  12.])

array([-4., -4., -4., -4.])

array([-4., -4., -4., -4.])

array([  5.,  12.,  21.,  32.])

array([  5.,  12.,  21.,  32.])

array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

array([ 1.,  2.,  3.,  4.])

array([ 1.,  2.,  3.,  4.])

array([ 1.0000e+00,  6.4000e+01,  2.1870e+03,  6.5536e+04])

array([ 1.0000e+00,  6.4000e+01,  2.1870e+03,  6.5536e+04])

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[ 0.2         0.33333333  0.42857143  0.5       ]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### Floor, Ceil and Rint

In [40]:
a = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])
np.floor(a)
np.ceil(a)
np.rint(a) #The rint tool rounds to the nearest integer of input element-wise

a = np.array(list(map(float, input().split())))
# np.set_printoptions(sign=' ')
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

array([ 1.,  2.,  3.,  4.,  5.,  6.])

array([ 2.,  3.,  4.,  5.,  6.,  7.])

array([ 1.,  2.,  3.,  4.,  6.,  7.])

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### Sum and Prod

In [47]:
my_array = np.array([ [1, 2], [3, 4] ])

np.sum(my_array, axis = 0)         #Output : [4 6]
np.sum(my_array, axis = 1)         #Output : [3 7]
np.sum(my_array, axis = None)      #Output : 10
np.sum(my_array)                  

np.prod(my_array, axis = 0)            #Output : [3 8]
np.prod(my_array, axis = 1)            #Output : [ 2 12]
np.prod(my_array, axis = None)         #Output : 24
np.prod(my_array)


n, m = map(int, input().split())
arr = np.array([list(map(int, input().split())) for i in range(n)])
print(np.prod(np.sum(arr, axis = 0)))

array([4, 6])

array([3, 7])

10

10

array([3, 8])

array([ 2, 12])

24

24

2 2
1 2
3 4
24


### Min and Max

In [48]:
n, m = map(int, input().split())
arr = np.array([list(map(int, input().split())) for i in range(n)])
print(np.max(np.min(arr, axis = 1)))

4 2
2 5
3 7
1 3
4 0
3


### Mean, Var and Std

In [49]:
n, m = map(int, input().split())
arr = np.array([list(map(int, input().split())) for i in range(n)])
print(np.mean(arr, axis = 1))
print(np.var(arr, axis = 0))
print(np.std(arr, axis = None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.118033988749895


### Dot and Cross

In [50]:
A = np.array([ 1, 2 ])
B = np.array([ 3, 4 ])

np.dot(A, B)       #Output: 11
np.cross(A, B)  # Output: -2

n = int(input())
a = []
for i in range(n):
    a.append(list(map(int, input().split())))
A = np.array(a).reshape((n, n))

b = []
for i in range(n):
    b.append(list(map(int, input().split())))
B = np.array(b).reshape((n, n))

print(np.dot(A, B))

11

array(-2)

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


### Inner and Outer

In [51]:
A = np.array([0, 1])
B = np.array([3, 4])

np.inner(A, B) # inner product
np.outer(A, B) # outer product


a = list(map(int, input().split()))
b = list(map(int, input().split()))

A = np.array(a)
B = np.array(b)

print(np.inner(A, B))
print(np.outer(A, B))

4

array([[0, 0],
       [3, 4]])

0 1
2 3
3
[[0 0]
 [2 3]]


### Polynomials

In [55]:
# poly tool returns the coefficients of a polynomial with the given sequence of roots
np.poly([-1, 1, 1, 10])

#  roots tool returns the roots of a polynomial with the given coefficients
np.roots([1, 0, -1])

#  polyint tool returns an antiderivative (indefinite integral) of a polynomial.
np.polyint([1, 1, 1])

# polyder tool returns the derivative of the specified order of a polynomial.
np.polyder([1, 1, 1, 1])       #Output : [3 2 1]

# polyval tool evaluates the polynomial at specific value.
np.polyval([1, -2, 0, 2], 4)   #Output : 34

# polyfit tool fits a polynomial of a specified order to a set of data using a least-squares approach
np.polyfit([0, 1, -1, 2, -2], [0, 1, 1, 4, 4], 2)


coe = list(map(float, input().split()))
val = float(input())
print(np.polyval(coe, val))

array([  1., -11.,   9.,  11., -10.])

array([ 1., -1.])

array([ 0.33333333,  0.5       ,  1.        ,  0.        ])

array([3, 2, 1])

34

array([  1.00000000e+00,   0.00000000e+00,   1.98602732e-16])

1.1 2 3
0
3.0


### Linear Algebra

In [52]:
# linalg.det tool computes the determinant of an array.
np.linalg.det([[1 , 2], [2, 1]])

# linalg.eig computes the eigenvalues and right eigenvectors of a square array.
vals, vecs = np.linalg.eig([[1 , 2], [2, 1]])
vals
vecs

# linalg.inv tool computes the (multiplicative) inverse of a matrix.
np.linalg.inv([[1 , 2], [2, 1]])


n = int(input())
arr = np.array([list(map(float, input().split())) for i in range(n)])
np.linalg.det(arr)

-2.9999999999999996

array([ 3., -1.])

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

2
1.1 1.1
1.1 1.1


0.0